### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by macta** [juliangrigera/PharoTweaks#1]
Not a bug or an issue, but wanted to thank you for this - its been driving me crazy not being able to flip between windows easily and I didn't know about this little baseline.

It should be proposed for P8 officially. Thanks

**Comment by juliangrigera** [comment]
Haha, this is a great "issue" to have, thanks!
I actually need to start working on P9 because a lot has changed and it won't work out of the box. Also must make it cross-platform so it's worth proposing as part of the base image.
